name: Daily Selenium Scraper

on:
  schedule:
    - cron: "30 20 * * *"  # 2:00 AM IST
    - cron: "30 2 * * *"   # 8:00 AM IST
    - cron: "30 6 * * *"   # 12:00 PM IST
    - cron: "30 10 * * *"  # 4:00 PM IST
  workflow_dispatch:

jobs:
  run-scrapers:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        subject: [DAA_extended.py, CN_extended.py, DEVOPS_extended.py, PPL_extended.py, NLP_extended.py, CN_LAB_extended.py]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromium-browser
          which chromedriver
          pip install -r requirements.txt

      - name: Create Google credentials files
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
          echo '${{ secrets.GOOGLE_CREDENTIALS1 }}' > credentials1.json
          echo '${{ secrets.GOOGLE_CREDENTIALS2 }}' > credentials2.json

      - name: Get current time in IST
        id: runtime
        run: |
          export TZ=Asia/Kolkata
          echo "now=$(date '+%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_OUTPUT

      - name: Run scraper for ${{ matrix.subject }}
        run: |
          python ${{ matrix.subject }}

  notify:
    needs: run-scrapers
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Selenium Scraper Finished (Status: ${{ job.status }})"
          to: nnrg.edu.in@gmail.com
          from: "GitHub Actions Bot <${{ secrets.MAIL_USERNAME }}>"
          html_body: |
            <!DOCTYPE html>
            <html>
            ...
            ⏰ <strong>Run Time:</strong> See individual job logs.
            ...
            </html>
