name: Daily Selenium Scraper

on:
  schedule:
    - cron: "30 20 * * *"  # 2:00 AM IST
    - cron: "30 2 * * *"   # 8:00 AM IST
    - cron: "30 6 * * *"   # 12:00 PM IST
    - cron: "30 10 * * *"  # 4:00 PM IST
  workflow_dispatch:

jobs:
  run-scrapers:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        subject: [DAA_extended.py, CN_extended.py, DEVOPS_extended.py, PPL_extended.py, NLP_extended.py, CN_LAB_extended.py, DEVOPS_LAB_extended.py, ACS_LAB_extended.py]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromium-browser
          which chromedriver
          pip install -r requirements.txt

      - name: Create Google credentials files
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
          echo '${{ secrets.GOOGLE_CREDENTIALS1 }}' > credentials1.json
          echo '${{ secrets.GOOGLE_CREDENTIALS2 }}' > credentials2.json
          echo '${{ secrets.GOOGLE_CREDENTIALS3 }}' > credentials3.json

      - name: Get current time in IST
        id: runtime
        run: |
          export TZ=Asia/Kolkata
          echo "now=$(date '+%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_OUTPUT

      - name: Run scraper for ${{ matrix.subject }}
        run: |
          python ${{ matrix.subject }}

  notify:
    needs: run-scrapers
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Selenium Scraper Finished (Status: ${{ job.status }})"
          to: nnrg.edu.in@gmail.com
          from: "GitHub Actions Bot <${{ secrets.MAIL_USERNAME }}>"
          html_body: |
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Daily Attendance Scraper Report</title>
              <style>
                body {
                  font-family: Arial, sans-serif;
                  margin: 0;
                  padding: 0;
                  background-color: #f5f8fa;
                  font-size: 12px;
                }
                .container {
                  max-width: 400px;
                  margin: 10px auto;
                  background-color: #ffffff;
                  border-radius: 14px;
                  border: 1px solid #e6ecf0;
                  overflow: hidden;
                }
                .header-img {
                  width: 100%;
                  height: 70px;
                  object-fit: cover;
                  display: block;
                  border-bottom: 1px solid #e6ecf0;
                }
                .report-header {
                  text-align: center;
                  padding: 8px;
                  background: #f9fbfc;
                  border-bottom: 1px solid #e6ecf0;
                }
                .report-header h2 {
                  margin: 0;
                  font-size: 14px;
                  font-weight: bold;
                  color: #14171a;
                }
                .report-header p {
                  margin: 2px 0;
                  font-size: 11px;
                  color: #657786;
                }
                .content {
                  padding: 10px 12px;
                  color: #14171a;
                  font-size: 12px;
                  line-height: 1.5;
                }
                .status-box {
                  margin: 10px 0;
                  padding: 6px;
                  background: #f1f8ff;
                  border-left: 3px solid #1da1f2;
                  border-radius: 8px;
                  font-size: 12px;
                }
                .buttons {
                  text-align: center;
                  margin: 12px 0;
                }
                .btn {
                  display: inline-block;
                  padding: 3px 90px;
                  margin: 4px;
                  text-decoration: none;
                  color: white;
                  border-radius: 20px;
                  font-size: 12px;
                  font-weight: bold;
                }
                .btn-blue {
                  background-color: #657786;
                  padding: 3px 87px;
                }
                .btn-red {
                  background-color: red;
                  padding: 3px 94px;
                }
                .btn-gray {
                  background-color: #1da1f2;
                  padding: 3px 80px;
                }
                .footer {
                  text-align: center;
                  padding: 6px;
                  font-size: 11px;
                  color: #657786;
                  border-top: 1px solid #e6ecf0;
                }
              </style>
            </head>
            <body>
              <div class="container">
                <!-- Header Image -->
                <img src="https://images.unsplash.com/photo-1557989048-03456d01a26e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzB8fGNsYXNzJTIwYXR0ZW5kZW5jZSUyMHJlcG9ydHxlbnwwfHwwfHx8MA%3D%3D"
                     alt="Attendance" class="header-img">

                <!-- Header -->
                <div class="report-header">
                  <h2>Daily Attendance Scraper Report</h2>
                  <p>${{ github.event_name }} | Run #${{ github.run_number }}</p>
                </div>

                <!-- Content -->
                <div class="content">
                  <strong>Hello Nikki 👋,</strong>
                  <p>The Selenium scraper has finished running.</p>

                  <!-- Status Box -->
                  <div class="status-box">
                    📌 <strong>Status:</strong> <b>${{ job.status }}</b><br>
                    ⏰ <strong>Run Time:</strong> ${{ steps.runtime.outputs.now }}
                  </div>

                  <p>📄 Click below to view:</p>

                  <!-- Buttons -->
                  <div class="buttons">
                    <!-- Google Sheet -->
                    <a href="https://docs.google.com/spreadsheets/d/168dU0XLrRkVZQquAStktg_X9pMi3Vx9o9fOmbUYOUvA/edit?gid=728086314#gid=728086314"
                       class="btn btn-blue">📖 Open Sheet</a><br>

                    <!-- Dynamic Logs Link -->
                    <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                       class="btn btn-red">📜 View Logs</a><br>

                    <!-- Retry Workflow Link -->
                    <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                       class="btn btn-gray">🔄 Retry Workflow</a>
                  </div>

                  <p>Keep track easily! 🚀</p>
                  <p>Cheers,<br>Automation Bot 🤖</p>
                </div>


                <!-- Footer -->
                <div class="footer">
                  Auto Email | GitHub Actions
                </div>
              </div>
            </body>
            </html>
